ACTIVE_PROFILE: prod

PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"

POSTGRES_USERNAME: ***REMOVED_USER***
POSTGRES_PASSWORD: ***REMOVED***
POSTGRES_HOST: 127.0.0.1
POSTGRES_PORT: 5432
POSTGRES_DATABASE: medilabo_patient

USER_NAME: ${USER_NAME}
PASSWORD: ${PASSWORD}
ROLES: ${ROLES}

SERVER_PORT: 8080
UI_APP_URL: http://localhost:4200