ACTIVE_PROFILE: dev

PRIVATE_KEY:
PUBLIC_KEY:

POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_USER: ***REMOVED_USER***
POSTGRES_PASSWORD: ***REMOVED***
POSTGRES_DATABASE: openclassrooms_medical_microservice

USER_NAME: admin
PASSWORD: ***REMOVED_USER***
ROLE: EUREKA_CLIENT

server: 8080
UI_APP_URL: http://localhost:4200